#!/usr/bin/env python3
"""
sync-constitution.py v0.4.0

Sync architect-constitution.md and smart-router.md from sources.
- Reads smart-router.yaml (truth database for routing)
- Generates smart-router.md (readable markdown table)
- Extends architect-constitution.md with metadata

Usage:
  python sync-constitution.py --constitution    # Only constitution
  python sync-constitution.py --router          # Only smart-router
  python sync-constitution.py                   # Both (default)

Exit codes:
  0 = success
  1 = validation/parsing error
  2 = critical error (filesystem, permissions)
"""

import argparse
import sys
import os
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install pyyaml")
    sys.exit(2)


__version__ = "0.4.0"
SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parent.parent  # Assume: scripts/sync-constitution.py → repo_root


def get_commit_hash():
    """Get current git commit hash if available."""
    try:
        import subprocess
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"


def generate_header(description: str) -> str:
    """Generate markdown header with metadata."""
    timestamp = datetime.utcnow().isoformat() + "Z"
    commit = get_commit_hash()
    return f"""<!-- 
Generated by sync-constitution.py v{__version__}
Generated: {timestamp}
Commit: {commit}
Source: {description}
DO NOT EDIT MANUALLY — regenerate with sync-constitution.py
-->

"""


def load_smart_router_yaml(yaml_path: Path) -> dict:
    """Load and validate smart-router.yaml."""
    if not yaml_path.exists():
        raise FileNotFoundError(f"smart-router.yaml not found: {yaml_path}")
    
    try:
        with open(yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        if hasattr(e, 'problem_mark'):
            mark = e.problem_mark
            raise ValueError(f"YAML Syntax Error at line {mark.line+1}, column {mark.column+1}: {e.problem}")
        else:
            raise ValueError(f"Invalid YAML: {e}")
    
    if not isinstance(data, dict) or "domains" not in data:
        raise ValueError("smart-router.yaml must have 'domains' key at root")
    
    return data


def generate_smart_router_md(router_yaml: dict) -> str:
    """Generate smart-router.md from YAML."""
    content = generate_header("smart-router.yaml")
    content += "# Smart Router — Domain → Skill Mapping\n\n"
    content += "> Automatically generated. Maintain `smart-router.yaml` as source of truth.\n\n"
    
    domains = router_yaml.get("domains", [])
    
    for domain in domains:
        name = domain.get("name", "unknown")
        content += f"## Domínio: {name.capitalize()}\n\n"
        content += "| Intenção detectada | Palavras-chave / Padrões | Skill / Agente |\n"
        content += "|---|---|---|\n"
        
        intents = domain.get("intents", [])
        for intent in intents:
            pattern = intent.get("pattern", "unknown")
            keywords_list = intent.get("keywords", [])
            keywords = ", ".join(f'"{k}"' for k in keywords_list) if keywords_list else "-"
            skill = intent.get("skill", "unknown")
            gate = intent.get("gate", "")
            
            skill_text = f"`{skill}`"
            if gate:
                skill_text += f" (Gate: {gate})"
                
            content += f"| {pattern.capitalize()} | {keywords} | {skill_text} |\n"
        
        content += "\n"
    
    return content


def sync_constitution(constitution_path: Path) -> str:
    """Ensure architect-constitution.md has metadata header."""
    if not constitution_path.exists():
        raise FileNotFoundError(f"architect-constitution.md not found: {constitution_path}")
    
    with open(constitution_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # TODO: Add metadata validation here (Articles I-V presence, etc.)
    # For now, just ensure header exists
    if not content.startswith("<!--"):
        content = generate_header("architect-constitution.md") + content
    
    return content


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--constitution",
        action="store_true",
        help="Only sync architect-constitution.md"
    )
    parser.add_argument(
        "--router",
        action="store_true",
        help="Only sync smart-router.md"
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Verbose output"
    )
    
    args = parser.parse_args()
    
    # Default: sync both
    sync_constitution_md = not args.router or (args.constitution and args.router)
    sync_router_md = not args.constitution or (args.constitution and args.router)
    
    try:
        rules_dir = REPO_ROOT / "rules"
        scripts_dir = REPO_ROOT / "scripts"
        
        # Sync Router
        if sync_router_md:
            if args.verbose:
                print("[*] Syncing smart-router.md...")
            
            yaml_path = rules_dir / "smart-router.yaml"
            router_yaml = load_smart_router_yaml(yaml_path)
            router_md_content = generate_smart_router_md(router_yaml)
            
            output_path = rules_dir / "smart-router.md"
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(router_md_content)
            
            if args.verbose:
                print(f"[✓] Generated: {output_path}")
        
        # Sync Constitution
        if sync_constitution_md:
            if args.verbose:
                print("[*] Syncing architect-constitution.md...")
            
            constitution_path = rules_dir / "architect-constitution.md"
            constitution_content = sync_constitution(constitution_path)
            
            with open(constitution_path, "w", encoding="utf-8") as f:
                f.write(constitution_content)
            
            if args.verbose:
                print(f"[✓] Updated: {constitution_path}")
        
        if args.verbose:
            print("[✓] All syncs completed successfully")
        
        return 0
    
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"CRITICAL ERROR: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
